"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['fisheries_gui.py']
DATA_FILES = ['images','images/about.png','images/fish.ico','images/fish.png','images/fishnet.ico','images/fishnet.png','images/seafoodcrc.png','images/Top Menu_fishing boats.gif']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
